[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200
runOnSave = false
allowRunOnSave = false
fileWatcherType = "none"

[browser]
gatherUsageStats = false

[theme]
base = "light"

[global]
developmentMode = false
showWarningOnDirectExecution = false

[logger]
level = "error"
messageFormat = "%(asctime)s %(message)s" 